version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    ports:
      - "8090:80"
    depends_on:
      - redis_server
  worker:
    build:
      dockerfile: DockerfileCelery
      context: .
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    depends_on:
      - redis_server
      
  redis_server:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    command: ["celery", "--broker=redis://redis_server:6379/0", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server
